name: I just think you of I

on:
  push:
    paths-ignore:
      - 'update.json'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: Smile
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Get version
        id: get_version
        shell: bash
        run: |
          VERSION=$(grep '^version=' ./module.prop | cut -d'=' -f2)
          VERSION_CODE=$(grep '^versionCode=' ./module.prop | cut -d'=' -f2)

          echo "version=$VERSION" >> "$GITHUB_OUTPUT"
          echo "version_code=$VERSION_CODE" >> "$GITHUB_OUTPUT"

      - name: Build!
        shell: bash
        run: |
          zip -r colorosshowtw-v${{ steps.get_version.outputs.version }}.zip module.prop system/

      - name: Release
        uses: softprops/action-gh-release@master
        with:
          tag_name: v${{ steps.get_version.outputs.version }}
          files: colorosshowtw-v${{ steps.get_version.outputs.version }}.zip
          body: |
            # 📝 更新日志
            - 修复和改进
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update update.json
        shell: bash
        run: |
          VERSION="${{ steps.get_version.outputs.version }}"
          VERSION_CODE="${{ steps.get_version.outputs.version_code }}"

          cat > update.json <<EOF
          {
            "version": "${VERSION}",
            "versionCode": ${VERSION_CODE},
            "zipUrl": "https://github.com/${{ github.repository }}/releases/download/v${VERSION}/colorosshowtw-v${VERSION}.zip",
            "changelog": "https://github.com/${{ github.repository }}/releases/tag/v${VERSION}"
          }
          EOF

          cat update.json

          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add update.json
          git commit -m "Bump update.json version"
          git push
